/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BackToTop: typeof import('./src/components/BackToTop.vue')['default']
    CallTable: typeof import('./src/components/relations/CallTable.vue')['default']
    FamilyTree: typeof import('./src/components/relations/FamilyTree.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    HeroSection: typeof import('./src/components/home/HeroSection.vue')['default']
    MarkDownViewer: typeof import('./src/components/MarkDownViewer.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    NavigationBar: typeof import('./src/components/NavigationBar.vue')['default']
    RelationNetwork: typeof import('./src/components/relations/RelationNetwork.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarNav: typeof import('./src/components/relations/SidebarNav.vue')['default']
    StarryBackground: typeof import('./src/components/home/StarryBackground.vue')['default']
  }
}
